# Generated by Django 4.0.4 on 2022-06-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_snsubscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snsubscribe',
            old_name='subscribe',
            new_name='section',
        ),
    ]
