# Generated by Django 4.0.3 on 2022-06-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_comments'),
        ('blogapp', '0004_rename_subscribe_snsubscribe_section'),
    ]

    operations = [
    ]
