# Generated by Django 4.0.3 on 2022-06-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_likedislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='snposts',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='snposts',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
