# Generated by Django 4.0.4 on 2022-06-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
