# Generated by Django 4.0.3 on 2022-06-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snposts',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
