# Generated by Django 4.0.4 on 2022-06-22 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('blogapp', '0010_notifications_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='notifier',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='post',
        ),
        migrations.AddField(
            model_name='notifications',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='from_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_notifier', to=settings.AUTH_USER_MODEL, verbose_name='Уведомитель'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='notifications',
            name='to_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_getter', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
