# Generated by Django 4.0.4 on 2022-06-22 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0011_remove_notifications_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_notifier', to=settings.AUTH_USER_MODEL, verbose_name='Уведомитель'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_getter', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
