# Generated by Django 4.0.3 on 2022-06-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_alter_snposts_is_active'),
        ('blogapp', '0010_snfavorites'),
        ('blogapp', '0012_alter_notifications_content_type_and_more'),
    ]

    operations = [
    ]
