# Generated by Django 4.0.4 on 2022-06-27 18:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_merge_20220624_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snposts',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст поста'),
        ),
    ]
