# Generated by Django 4.0.4 on 2022-06-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_alter_snposts_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='snposts',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='blogapp.ip'),
        ),
    ]
