# Generated by Django 4.0.4 on 2022-05-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SNSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название раздела')),
                ('description', models.TextField(verbose_name='Описание раздела')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
