# Generated by Django 4.0.4 on 2022-05-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsections',
            name='title',
            field=models.CharField(default='Title', max_length=30, verbose_name='Title раздела'),
            preserve_default=False,
        ),
    ]
