# Generated by Django 4.0.4 on 2022-05-31 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_snsections_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название поста')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Превьюшка поста')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('short_desc', models.CharField(max_length=255, verbose_name='Краткое описание поста')),
                ('description', models.TextField(verbose_name='Описание поста')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.snsections', verbose_name='Раздел поста')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Раздел поста')),
            ],
        ),
    ]
