# Generated by Django 4.0.4 on 2022-06-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snuserprofile',
            name='gender',
        ),
    ]
